[base]
package = ocean
env_name = puffer_tileblast
policy_name = Policy

[env]
; Single learning agent; environment spawns 3 patrolling opponents.
num_agents = 1
num_envs = 1
width = 11
height = 9
agent_speed = 1
max_steps = 1000
vision = 0

[vec]
num_envs = 16
num_workers = 2

[train]
total_timesteps = 500_000
gamma = 0.99
gae_lambda=0.95
learning_rate = 0.0002
minibatch_size = 256
ent_coef = 0.005
device = cuda
precision = float32
optimizer = adam
compile = False
anneal_lr=True