[base]
package = ocean
env_name = puffer_tileblast
policy_name = Policy

[env]
; 1 for single-agent (vs bot), 2 for two-agent (self-play)
num_agents = 2
num_envs = 2048
width = 11
height = 9
max_steps = 500
vision = 0

[vec]
num_envs = 16
num_workers = 2

[train]
total_timesteps = 50000000
gamma = 0.99
learning_rate = 0.0006
minibatch_size = 8192
ent_coef = 0.01
device = cpu
precision = float32
optimizer = muon
